linters:
  presets:
    - bugs
    - complexity
    - format
    - performance
    - unused
    - style
  disable:
    - paralleltest
    - wrapcheck
    - exhaustivestruct
    - whitespace
    - wsl
    - godot
    - lll
    - funlen
    - gomnd
    - gofumpt
    - maligned
    - unparam
    - tagliatelle
    - forbidigo
    - gci
    - varnamelen
    - exhaustruct
    - depguard
    - nolintlint
run:
  tests: false
issues:
  fix: false
    