project_name: ticker
before:
  hooks:
    - go mod download
builds:
  - id: build-linux-64
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx "{{ .Path }}"
    ldflags:
      - -s -w -X 'github.com/achannarasappa/ticker/v4/cmd.Version={{.Version}}'
  - id: build-linux
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - arm
      - arm64
    hooks:
      post:
        - upx "{{ .Path }}"
    ldflags:
      - -s -w -X 'github.com/achannarasappa/ticker/v4/cmd.Version={{.Version}}'
  - id: build-mac
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    ldflags:
      - -s -w -X 'github.com/achannarasappa/ticker/v4/cmd.Version={{.Version}}'
  - id: build-windows-64
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - windows
    ldflags:
      - -s -w -X 'github.com/achannarasappa/ticker/v4/cmd.Version={{.Version}}'
  - id: build-windows-32
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goarch:
      - 386
    goos:
      - windows
    ldflags:
      - -s -w -X 'github.com/achannarasappa/ticker/v4/cmd.Version={{.Version}}'
archives:
  - id: release-winget
    format: zip
    builds:
      - build-windows-64
    name_template: >-
      {{- .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}mac
      {{- else}}{{ .Os }}{{ end }}-
      {{- .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}-{{ .Mips }}{{ end }}
  - id: release
    format: tar.gz
    name_template: >-
      {{- .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Os "darwin" }}mac
      {{- else}}{{ .Os }}{{ end }}-
      {{- .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
      {{- if .Mips }}-{{ .Mips }}{{ end }}
snapshot:
  name_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
release:
  github:
      owner: achannarasappa
      name: ticker
brews:
  -
    name: ticker
    tap:
      owner: achannarasappa
      name: tap
    commit_author:
      name: achannarasappa
      email: git@ani.dev
    homepage: "https://github.com/achannarasappa/ticker"
    description: "Terminal stock ticker with live updates and position tracking"
    license: "GPLv3"
dockers:
- image_templates: ["achannarasappa/ticker:{{ .Version }}-amd64"]
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--platform=linux/amd64"
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
- image_templates: ["achannarasappa/ticker:{{ .Version }}-arm64v8"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - "--platform=linux/arm64/v8"
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.title={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
docker_manifests:
- name_template: achannarasappa/ticker:{{ .Version }}
  image_templates:
  - achannarasappa/ticker:{{ .Version }}-amd64
  - achannarasappa/ticker:{{ .Version }}-arm64v8
- name_template: achannarasappa/ticker:latest
  image_templates:
  - achannarasappa/ticker:{{ .Version }}-amd64
  - achannarasappa/ticker:{{ .Version }}-arm64v8
- name_template: achannarasappa/ticker:{{ .Major }}
  image_templates:
  - achannarasappa/ticker:{{ .Version }}-amd64
  - achannarasappa/ticker:{{ .Version }}-arm64v8
- name_template: achannarasappa/ticker:{{ .Major }}.{{ .Minor }}
  image_templates:
  - achannarasappa/ticker:{{ .Version }}-amd64
  - achannarasappa/ticker:{{ .Version }}-arm64v8
- name_template: achannarasappa/ticker:{{ .Major }}.{{ .Minor }}.{{ .Patch }}
  image_templates:
  - achannarasappa/ticker:{{ .Version }}-amd64
  - achannarasappa/ticker:{{ .Version }}-arm64v8
nfpms:
  -
    file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    builds:
      - build-linux-64
    homepage: https://github.com/achannarasappa/ticker
    maintainer: Ani Channarasappa <ticker@ani.dev>
    description: Terminal stock ticker with live updates and position tracking
    license: GPLv3
    formats:
      - deb
      - rpm
# snapcrafts:
#   -
#     id: ticker
#     name_template: >-
#       {{- .ProjectName }}-
#       {{- .Version }}-
#       {{- if eq .Os "darwin" }}mac
#       {{- else}}{{ .Os }}{{ end }}-
#       {{- .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
#       {{- if .Mips }}-{{ .Mips }}{{ end }}
#     publish: true
#     summary: Terminal stock watcher and stock position tracker
#     description: |
#       Features:
#       Live stock price quotes
#       Track value of your stock positions
#       Support for multiple cost basis lots
#       Support for pre and post market price quotes

#     grade: stable
#     confinement: strict
#     apps:
#       ticker:
#         plugs: ["network", "home"]
