name: contract test

on: 
  schedule:
    - cron:  '* 23 * * *'

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Ginkgo
      run: go get -u github.com/onsi/ginkgo/ginkgo
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: ginkgo -cover -focus="GetQuotes Response" ./...
