name: test-contract

on: 
  schedule:
    - cron:  '0 8 * * *'
  push:
    branches: [ master ]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.26.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test Quote API
      run: go tool ginkgo -r -v ./test/contract/yahoo/ -focus "GetAssetQuotes Response"
