name: test-contract

on: 
  schedule:
    - cron:  '0 8 * * *'
  push:
    branches: [ master ]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test
      run: go run github.com/onsi/ginkgo/ginkgo@v1.16.5 -r -v ./internal/quote/yahoo/ -focus "GetQuotes Response"
